---
title: "Ćwiczenie_2"
author: "Łukasz Bilański"
format: 
  html:
    self-contained: true
    embed-resources: true
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "Spis treści"
    number-sections: true
    number-depth: 4
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    code-block-bg: true
    code-block-border-left: "black"
    code-line-numbers: false
    code-copy: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    theme:
        light: cosmo
        dark: darkly
    fontsize: 1.0em
    linestretch: 1.5
execute:
  warning: false
  echo: true
  error: false
---

##Potrzebne biblioteki

```{r}
#| echo: false
library(tidymodels)
library(parsnip)
library(dplyr)
# Helper packages
library(readr)# import danych
library(broom.mixed) # konwersja 
library(dotwhisker)  # wizualizacja
library(GGally) # wizualizacja
```

## Wstępne przetwarzanie danych 

```{r}
library(skimr)
library(nycflights13)
library(tidymodels)
tidymodels_prefer()
```

```{r}
?flights
?weather
```

```{r}
set.seed(123)
flights_data <-
  flights |>
  mutate(
    arr_delay = ifelse(arr_delay >= 30, "late", "on_time"),
    arr_delay = factor(arr_delay),
    date = lubridate::as_date(time_hour)
  ) |>
  inner_join(weather, by = c("origin", "time_hour")) |>
  select(dep_time,
         flight,
         origin,
         dest,
         air_time,
         distance,
         carrier,
         date,
         arr_delay,
         time_hour) |>
  na.omit() |>
  mutate_if(is.character, as.factor)
```


```{r}
flights_data |>
  count(arr_delay)
```

```{r}
flights_data |>
  count(arr_delay) |>
  mutate(prop = n/sum(n))
```


```{r}
flights_data |> glimpse()
```
```{r}
flights_data |>
  skimr::skim()
```

```{r}
set.seed(222)
data_split <- initial_split(data = flights_data, prop = 3/4)
train_data <- training(data_split)
test_data <-  testing(data_split)
```

```{r}
flights_rec <-
  recipe(arr_delay ~., data = train_data)
```

```{r}
flights_rec <-
  recipe(arr_delay ~ ., data = train_data) |>
  update_role(flight, time_hour, new_role = "ID")
```

```{r}
flights_rec <- 
  recipe(arr_delay ~ ., data = train_data) |> 
  update_role(flight, time_hour, new_role = "ID") |> 
  step_date(date, features = c("dow", "month")) |> 
  step_holiday(date, 
               holidays = timeDate::listHolidays("US"), 
               keep_original_cols = F)

flights_rec |> summary()
```

```{r}
flights_rec |> prep() |> bake(train_data) |> _[1:10,] |> DT::datatable()
```


```{r}
library(tzdb)
library(recipes)
library(timeDate)
```

```{r}
flights_rec <- 
  recipe(arr_delay ~ ., data = train_data) |> 
  update_role(flight, time_hour, new_role = "ID") |> 
  step_date(date, features = c("dow", "month")) |> 
  step_holiday(date, 
               holidays = timeDate::listHolidays("US"), 
               keep_original_cols = F) |> 
  step_dummy(all_nominal_predictors())

flights_rec |> summary()
```


```{r}
test_data |> 
  distinct(dest) |> 
  anti_join(train_data)
```

```{r}
flights_rec <-
  recipe(arr_delay ~ ., data = train_data) |>
  update_role(flight, time_hour, new_role = "ID") |>
  step_date(date, features = c("dow", "month")) |>
  step_holiday(date,
               holidays = timeDate::listHolidays("US"),
               keep_original_cols = F) |>
  step_dummy(all_nominal_predictors()) |>
  step_zv(all_predictors())
```


```{r}
flights_rec |> prep()
```

```{r}
lr_mod <- 
  logistic_reg() |> 
  set_engine("glm")
```


```{r}
logi_work <- 
  workflow() |> 
  add_model(lr_mod) |> 
  add_recipe(flights_rec)

logi_work
```

```{r}
logi_fit <-  
  logi_work |> 
  fit(data = train_data)


flights_rec |> summary()
```



```{r}
logi_fit |> 
  extract_fit_parsnip() |> 
  tidy()
```


```{r}
logi_fit |> 
  extract_recipe()
```


```{r}
predict(logi_fit, test_data)
```


```{r}
predict(logi_fit, test_data, type = "prob")
```

```{r}
pred_test <- 
  augment(logi_fit, test_data) |>
  select(-dest,
         -flight,
         -origin,
         -dep_time,
         -air_time,
         -distance,
         -carrier,
         -date)
pred_test
```

```{r}
pred_test  |> 
  roc_curve(truth = arr_delay, .pred_late) |> 
  autoplot()
```

```{r}
pred_test |> 
  roc_auc(truth = arr_delay, .pred_late)
```






